### ISSUE TITLE
New repo icon/banner

### ISSUE THREAD

**Issue by RCNOverwatcher** [Harry-Hopkinson/code-boilerplate#39]
![icon](https://user-images.githubusercontent.com/49075095/193450863-02863f9d-fb8c-4b5f-81d1-6efbef45f6ae.png)
![hello world banner](https://user-images.githubusercontent.com/49075095/193450864-30b820f8-b87c-4a56-826c-c709c452c9de.jpg)
![hello world logo](https://user-images.githubusercontent.com/49075095/193450874-b73e8c41-ded2-4e9d-ade2-cfce85cc93a5.jpg)

Tell me if any of these look good and I'll open a PR

**Comment by Harry-Hopkinson** [comment]
They look really good
